### ISSUE TITLE
False positives while using elytra.

### ISSUE THREAD

**Issue by makkarakka3** [JustDoom/FlappyAC#18]
Something like landing with an elytra from a short distance triggers Speed A and Jump A.

**Comment by JustDoom** [comment]
Was this with the beta versions of dev builds of the full release?

**Comment by makkarakka3** [comment]
This was on the newest version found on Spigot.

**Comment by JustDoom** [comment]
Ok, Ill update soon

**Comment by makkarakka3** [comment]
Ok. Thanks!

**Comment by JustDoom** [comment]
Should be fixed in the latest commit. It will also be fixed in the full release
